service: my-express-application

provider:
  name: aws
  runtime: nodejs8.11.4
  stage: dev
  region: ap-southeast-1

function:
  app:
    handler: index.handler
    events: 
      - http: ANY /
      - http: 'ANY {proxy+}'